### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by rovale** [pimatic/decl-api#1]
I have an issue with my Windows Phone. I can turn a specific device on and off only once. If I try to turn it on again, the application says it's done, while actually nothing happened. If I clear the browser cache, I can repeat this one more time.

I found out it is a caching issue. Chrome reports a 304 (not modified) response. Would it be caused because the http GET method is used instead of the POST method?

 For now I added some http headers to prevent the caching. This fixes the issue for me:

``` js
sendSuccessResponse = function(res, data) {
  if (data == null) {
    data = {};
  }
  data.success = true;
  res.header("Cache-Control", "no-cache, no-store, must-revalidate");
  res.header("Pragma", "no-cache");
  res.header("Expires", 0);
  return res.send(200, data);
};
```

Kind regards,
Ronald

**Comment by sweetpi** [comment]
That could be the root of other problems like the update check, too. Thanks for the notice. I've updated the package and released a new pimatic version with the updated version of the package. I'm thinking that it is maybe a good idea to switch to post requests, too.

**Comment by rovale** [comment]
Thanks for the prompt response and the updated version!

**Comment by sweetpi** [comment]
You are welcome.
