### ISSUE TITLE
Incorrect license listed under package.json

### ISSUE THREAD

**Issue by c-okelly** [pimatic/decl-api#3]
License is listed as GPL in package.json

Could you please update your license to SPDX format.

I have created #4  in relation. 

Update license to correct SPDX format for 'MIT'

Docs.
Yarn: https://yarnpkg.com/lang/en/docs/package-json/#toc-license
NPM: https://docs.npmjs.com/files/package.json#license
SPDX: https://spdx.org/licenses/MIT.html

**Comment by mwittig** [comment]
Thanks. Merged PR #4
